package edu.gatech.gtri.trustmark.grails.trpt.service.permission;

import org.gtri.fj.data.List;

import static edu.gatech.gtri.trustmark.grails.trpt.service.permission.Role.ROLE_ADMINISTRATOR;
import static edu.gatech.gtri.trustmark.grails.trpt.service.permission.Role.ROLE_ADMINISTRATOR_ORGANIZATION;
import static org.gtri.fj.data.List.arrayList;
import static org.gtri.fj.data.List.nil;

public enum PermissionName implements Permission {
    ORGANIZATION_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    ORGANIZATION_INSERT(arrayList(ROLE_ADMINISTRATOR)),
    ORGANIZATION_UPDATE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    ORGANIZATION_DELETE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    USER_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    USER_INSERT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    USER_UPDATE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    USER_DELETE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    USER_SELECT_WITHOUT_ORGANIZATION(arrayList(ROLE_ADMINISTRATOR)),

    PROFILE_SELECT(nil()),

    ROLE_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    TRUSTMARK_BINDING_REGISTRY_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    TRUSTMARK_BINDING_REGISTRY_INSERT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    TRUSTMARK_BINDING_REGISTRY_UPDATE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    TRUSTMARK_BINDING_REGISTRY_DELETE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    MAIL_SELECT(arrayList(ROLE_ADMINISTRATOR)),
    MAIL_UPDATE(arrayList(ROLE_ADMINISTRATOR)),
    MAIL_TEST(arrayList(ROLE_ADMINISTRATOR)),

    URI_SET_SELECT(arrayList(ROLE_ADMINISTRATOR)),

    PROTECTED_SYSTEM_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    PROTECTED_SYSTEM_INSERT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    PROTECTED_SYSTEM_UPDATE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),
    PROTECTED_SYSTEM_DELETE(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    PROTECTED_SYSTEM_TYPE_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION)),

    PARTNER_SYSTEM_CANDIDATE_SELECT(arrayList(ROLE_ADMINISTRATOR, ROLE_ADMINISTRATOR_ORGANIZATION));

    private List<Role> roleNameList;

    PermissionName(final List<Role> roleNameList) {
        this.roleNameList = roleNameList;
    }

    public List<Role> getRoleList() {
        return roleNameList;
    }
}
